import os
import secrets
from email.utils import format_datetime
from xml.etree.ElementTree import Element, SubElement, tostring

from app.models.podcast_episode import PodcastEpisode
from app.models.podcast_show import PodcastShow

_ITUNES_NS = "http://www.itunes.com/dtds/podcast-1.0.dtd"
_DESCRIPTION_MAX_CHARS = 300


def generate_feed_token() -> str:
    return secrets.token_urlsafe(32)


def _episode_description(episode: PodcastEpisode) -> str:
    if not episode.script:
        return ""
    text = " ".join(turn.get("text", "") for turn in episode.script).strip()
    return text[:_DESCRIPTION_MAX_CHARS]


def _episode_length_bytes(episode: PodcastEpisode, audio_dir: str) -> int:
    if not episode.audio_path:
        return 0
    try:
        return os.path.getsize(os.path.join(audio_dir, episode.audio_path))
    except OSError:
        return 0


def render_rss_feed(show: PodcastShow, episodes: list[PodcastEpisode], base_url: str, audio_dir: str) -> str:
    """Renders an RSS 2.0 + iTunes-namespace feed for `show`'s ready episodes.

    `episodes` should already be filtered to status == "ready" and ordered
    newest-first by the caller.
    """
    rss = Element("rss", {"version": "2.0", "xmlns:itunes": _ITUNES_NS})
    channel = SubElement(rss, "channel")
    SubElement(channel, "title").text = show.name
    SubElement(channel, "link").text = base_url
    SubElement(channel, "description").text = f"{show.name} — generated by Shoebill Feed"
    SubElement(channel, "language").text = show.language
    SubElement(channel, "itunes:author").text = "Shoebill Feed"
    SubElement(channel, "itunes:image", {"href": f"{base_url}/icon-512.png"})

    for episode in episodes:
        item = SubElement(channel, "item")
        pub_date = episode.generated_at or episode.created_at
        SubElement(item, "title").text = f"{show.name} — {pub_date.strftime('%B %-d, %Y')}"
        SubElement(item, "guid", {"isPermaLink": "false"}).text = str(episode.id)
        SubElement(item, "pubDate").text = format_datetime(pub_date)
        SubElement(item, "description").text = _episode_description(episode)
        if episode.audio_path:
            enclosure_url = f"{base_url}/api/podcasts/public/{show.public_feed_token}/episodes/{episode.id}/audio"
            SubElement(item, "enclosure", {
                "url": enclosure_url,
                "type": "audio/mpeg",
                "length": str(_episode_length_bytes(episode, audio_dir)),
            })
        if episode.duration_seconds:
            SubElement(item, "itunes:duration").text = str(episode.duration_seconds)

    return tostring(rss, encoding="utf-8", xml_declaration=True).decode("utf-8")
